# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9bdb5c0d185c422fddb2cb0069ec59b07537ec0569b200dfe934e63aadf8262501f8f92ee1a62e7a5a092f9d764cfa808f9b0f47b592c5ed8375224cd0cd2d0

test:
  secret_key_base: b5648adda10aa64caf64da5110359ff1c210a6a24a7fea455ccc6e18ecb85988e83c5989112c826e753f2cb911b1fbce58076744dc243107eada9cfc9c59f126

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
